// - auth
export const AUTH_CREATE = 'AUTH_CREATE'
export const AUTH_DATA_UPDATE = 'AUTH_DATA_UPDATE'
export const AUTH_DESTROY = 'AUTH_DESTROY'
export const AUTH_REFRESHTOKEN = 'AUTH_REFRESHTOKEN'

// - Profile
export const PROFILE_SHOW = 'PROFILE_SHOW'
export const PROFILE_CREATE = 'PROFILE_CREATE'

// - Workspace
export const WORKSPACE_SHOW = 'WORKSPACE_SHOW'
export const WORKSPACE_ASSIGN = 'WORKSPACE_ASSIGN'
export const WORKSPACE_CHANGE_CURRENT = 'WORKSPACE_CHANGE_CURRENT'
